# -------------------------------------------------------------------------
# CONFIGURACION DEL SERVIDOR
# -------------------------------------------------------------------------
server.port=${PORT:3000}

# -------------------------------------------------------------------------
# CONEXI\u00D3N DE MICROSERVICIOS DE IA (FastAPI)
# -------------------------------------------------------------------------
ai.service.base-url=${AI_SERVICE_BASE_URL:https://hrlafuente-psicaid-ai-backend.hf.space}
# -------------------------------------------------------------------------
# CONFIGURACION DE BASE DE DATOS
# -------------------------------------------------------------------------
# Usamos el puerto 6543 (Connection Pooler)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------------------------------------------------
# CONFIGURACION JPA / HIBERNATE
# -------------------------------------------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop #-- Descomentar en caso de querer eliminar los datos de la BD una vez y comentar el de abajo, luego volver a cambiar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ajustes para el Pooler de Supabase
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
# NUEVAS LINEAS PARA EVITAR FALLOS INTERMITENTES:
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.validation-timeout=3000

# -------------------------------------------------------------------------
# CORS
# -------------------------------------------------------------------------
spring.web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://i006-psicaid-fullstack.vercel.app/}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Authorization,Content-Type,X-Requested-With
spring.web.cors.allow-credentials=true

# -------------------------------------------------------------------------
# JWT SECURITY
# -------------------------------------------------------------------------
jwt.secret=${JWT_SECRET}