# -------------------------------------------------------------------------
# CONFIGURACION DEL SERVIDOR
# -------------------------------------------------------------------------
server.port=3000

# -------------------------------------------------------------------------
# CONEXI\u00D3N DE MICROSERVICIOS DE IA (FastAPI)
# -------------------------------------------------------------------------
ai.service.base-url=http://localhost:8000

# -------------------------------------------------------------------------
# CONFIGURACION DE BASE DE DATOS
# -------------------------------------------------------------------------
# Usamos el puerto 6543 (Connection Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.yrjrlrhznvpgvscnnkut
spring.datasource.password=CieloSol1122
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------------------------------------------------
# CONFIGURACION JPA / HIBERNATE
# -------------------------------------------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop -- Descomentar en caso de querer eliminar los datos de la BD una vez y comentar el de abajo, luego volver a cambiar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ajustes para el Pooler de Supabase
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# -------------------------------------------------------------------------
# CORS
# -------------------------------------------------------------------------
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:4173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Authorization,Content-Type,X-Requested-With
spring.web.cors.allow-credentials=true